# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Tests for 'eessi' command line tool
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: read # to fetch code (actions/checkout)
jobs:
  ubuntu-minimal:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14']
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - name: set up Python
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: ${{matrix.python}}

    - name: Install eessi command line tool
      id: install
      run: |
        export PREFIX=/tmp/$USER/$GITHUB_SHA
        pip install --prefix $PREFIX .
        echo "export PATH=$PREFIX/bin:$PATH" >> ~/env
        echo "export PYTHONPATH=$(ls -d $PREFIX/lib/python*/site-packages)" >> ~/env

    - name: Test 'eessi init' (without EESSI mounted)
      run: |
        source ~/env
        eessi init 2>&1 | grep "^ERROR: /cvmfs/software.eessi.io/versions/2023.06 does not exist"

    - name: Test 'eessi shell' (without EESSI mounted)
      run: |
        source ~/env
        eessi shell --eessi-version 2023.06 2>&1 | tee shell.out
        grep "No such file or directory" shell.out
        grep "^ERROR: Non-zero exit code detected for interactive shell" shell.out

    - name: Test 'eessi check' (without EESSI mounted)
      run: |
        source ~/env
        eessi check | tee check.out
        grep 'Checking for EESSI repositories...' check.out
        grep 'ERROR /cvmfs/software.eessi.io is NOT available' check.out
        grep 'Inspecting EESSI repository software.eessi.io...' check.out
        grep 'ERROR Revision (client):  UNKNOWN' check.out
        grep 'Client cache quota limit:  UNKNOWN' check.out
        grep 'ERROR Number of cache cleanups in last 24h:  UNKNOWN' check.out
        grep 'List of Stratum-1 mirror servers:  UNKNOWN' check.out

    - name: Mount EESSI CernVM-FS repository
      uses: cvmfs-contrib/github-action-cvmfs@bc6dae3b3c00a732994bacfac8f0902a3e422c53 # v5.4
      with:
        cvmfs_repositories: 'software.eessi.io'

    - name: Test 'eessi init'
      run: |
        source ~/env
        eessi init
        eval "$(eessi init)"

    - name: Test 'eessi shell'
      run: |
        source ~/env

        echo ">>> checking behaviour of 'eessi shell' without specifying EESSI version to use..."
        eessi shell 2>&1 | tee shell.out
        grep "EESSI version to use is not specified" shell.out

        echo ">>> checking environment of subshell created with 'eessi shell' for EESSI 2023.06"
        eessi shell --eessi-version 2023.06 <<< 'env | grep ^EESSI' 2>&1 | tee shell.out
        grep '^Found EESSI repo @ /cvmfs/software.eessi.io/versions/2023.06' shell.out
        grep '^Environment set up to use EESSI (2023.06), have fun' shell.out
        grep '^EESSI_VERSION=2023.06' shell.out

    - name: Test 'eessi check'
      run: |
        source ~/env
        eessi check | tee check.out
        grep 'Checking for EESSI repositories...' check.out
        grep 'OK /cvmfs/software.eessi.io is available' check.out
        grep 'Inspecting EESSI repository software.eessi.io...' check.out
        grep 'Revision (client): [0-9]\+' check.out
        grep 'Path to client cache directory: /var/lib/cvmfs/shared' check.out
        grep 'Client cache quota limit: [0-9.]\+ GiB' check.out
        grep 'Cache Usage:  [0-9]\+k / [0-9]\+k' check.out
        grep 'http://aws-eu-central-s1.eessi.science/cvmfs/software.eessi.io' check.out
        grep 'http://cvmfs-ext.gridpp.rl.ac.uk:8000/cvmfs/software.eessi.io' check.out
        grep 'WARNING Proxy servers: DIRECT (not recommended' check.out
        grep 'GeoAPI enabled: yes' check.out
        grep 'Client profile: single' check.out
